name: Test Submodule Update Action

on:
  push:
    branches:
      - feature/MATTER-5624
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-matter_sdk:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        target_branch: [main, release_2.8-1.5, feature/MATTER-5624]
    steps:
      - name: Checkout target branche
        uses: actions/checkout@v6
        with:
          ref: ${{ matrix.target_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update matter_sdk submodule
        if: github.ref_name == matrix.target_branch
        uses: SiliconLabsSoftware/matter_build_action/action@feature/MATTER-5624
        with:
          target_branch: ${{ matrix.target_branch }}
          app-id: ${{ vars.SILABSSW_MATTER_CI_BOT_APP_ID }}
          private-key: ${{ secrets.SILABSSW_MATTER_CI_BOT_APP_PRIVATE_KEY }}